AWSTemplateFormatVersion: 2010-09-09
Description: >
  Bundan sonra
  yazacaklarim
  aslinda 
  tek satir.  
  
Resources:
  FirstYamlInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d7a109bf30624c99
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups: 
        - !Ref FirstYamlSG
      Tags: 
        - Key: Name
          Value: Sait-CFN-Instance

  FirstYamlSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows only SSH Connection # Required
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
